# Generated by Django 2.0.1 on 2018-02-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(default='basic', max_length=200),
        ),
    ]
