# Generated by Django 2.0.1 on 2018-02-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20180212_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtag',
            old_name='blog_tag',
            new_name='blogtag',
        ),
    ]
