# Generated by Django 2.0.1 on 2018-02-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20180212_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='blogtag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogs.Tag'),
        ),
    ]
