# Generated by Django 2.0.1 on 2018-02-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20180212_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_value',
            field=models.IntegerField(default=0),
        ),
    ]
