# Generated by Django 2.0.1 on 2018-02-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_tag_tag_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtag',
            name='blogtag',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_value',
            field=models.IntegerField(default=1),
        ),
    ]
