# Generated by Django 2.0.1 on 2018-02-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20180212_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AddField(
            model_name='blogtag',
            name='blogtag',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog'),
        ),
    ]
