# Generated by Django 2.0.1 on 2018-02-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20180212_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
