# Generated by Django 2.0.1 on 2018-02-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20180212_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtag',
            old_name='blogtag',
            new_name='blogistag',
        ),
    ]
