# Generated by Django 2.0.1 on 2018-02-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20180212_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtag',
            old_name='blogistag',
            new_name='blogtag',
        ),
    ]
