# Generated by Django 2.0.1 on 2018-02-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20180215_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtag',
            name='blogtag',
        ),
        migrations.AddField(
            model_name='blogtag',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.Tag'),
        ),
    ]
