# Generated by Django 2.0.1 on 2018-02-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20180215_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtag',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogtag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
