# Generated by Django 2.0.1 on 2018-03-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20180215_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='tag_id',
            field=models.IntegerField(default='1', max_length=200),
        ),
    ]
